#SABER O TIPO DA VARIAVEL
a = input('digite algo:  ')
print ('O tipo primitivo desse valor é: ', type(a))
print ('so tem espaço? ', a.isspace())
print ('é um numero?', a.isnumeric())
print ('é alfabetico? ', a.isalpha())
print ('é alfanumerico? ', a.isalnum())
print ('esta em maiusculo? ', a.isupper())
print ('esta em minusculas? ', a.islower())
print ('esta capitalizada? ', a.istitle())
